name: Shell
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm, macos-latest, macos-15-intel, windows-latest ]
        ruby: [ ruby ]
    runs-on: ${{ matrix.os }}
    steps:
    - run: locale
    - run: env | grep -E 'LC|LANG'
    - run: locale -a
